In [1]:
import pandas as pd
fact_orders = pd.read_csv(r"D:\My Work\Project\fact_orders_clean.csv")

In [2]:
fact_orders.shape # Print the shape (rows, columns) of fact_orders.

(300, 11)

In [3]:
fact_orders.columns # Print all the columns name of fact_orders.

Index(['order_id', 'customer_id', 'customer_name', 'product_name', 'category',
       'quantity', 'unit_price', 'discount', 'region', 'status', 'order_date'],
      dtype='object')

In [4]:
print(fact_orders.dtypes) # print all column data type

order_id         object
customer_id      object
customer_name    object
product_name     object
category         object
quantity          int64
unit_price        int64
discount          int64
region           object
status           object
order_date       object
dtype: object

In [5]:
fact_orders.describe() # print summary of numerical column

         quantity   unit_price    discount
count  300.000000   300.000000  300.000000
mean     2.963333  1531.236667    3.950000
std      1.426689  1285.976797    5.560326
min      1.000000   199.000000    0.000000
25%      2.000000   649.000000    0.000000
50%      3.000000   999.000000    0.000000
75%      4.000000  1899.000000   10.000000
max      5.000000  4999.000000   15.000000

In [6]:
fact_orders.info() # print information about all column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       300 non-null    object
 1   customer_id    300 non-null    object
 2   customer_name  300 non-null    object
 3   product_name   300 non-null    object
 4   category       300 non-null    object
 5   quantity       300 non-null    int64
 6   unit_price     300 non-null    int64
 7   discount       300 non-null    int64
 8   region         300 non-null    object
 9   status         300 non-null    object
 10  order_date     291 non-null    object
dtypes: int64(3), object(8)
memory usage: 25.9+ KB

In [7]:
fact_orders.isnull().sum() # if there is any null count and print it

order_id         0
customer_id      0
customer_name    0
product_name     0
category         0
quantity         0
unit_price       0
discount         0
region           0
status           0
order_date       9
dtype: int64

In [8]:
fact_orders['order_date']=pd.to_datetime(fact_orders['order_date']) # conver orderdate into date format

In [9]:
fact_orders['revenue'] = fact_orders['quantity'] * fact_orders['unit_price'] * (1 - fact_orders['discount']/100)
fact_orders.head()

,order_id,customer_id,customer_name,product_name,category,quantity,unit_price,discount,region,status,order_date,revenue
0,ORD-1035,C015,Arjun Nair,Pen Drive 32Gb,Electronics,2,799,5,North,Completed,2024-12-07,1518.10
1,ORD-1174,C014,Meera Pillai,Resistance Bands,Sports,2,649,0,Unknown,Completed,2024-09-14,1298.00
2,ORD-1066,C009,Vikram Das,Yoga Mat,Sports,4,899,0,North,Returned,2024-10-11,3596.00
3,ORD-1101,C011,Rahul Verma,Smart Watch,Electronics,1,4999,10,South,Completed,2024-08-13,4499.10
4,ORD-1109,C008,Neha Sharma,Protein Powder,Health,1,1899,15,South,Completed,2024-05-10,1614.15

In [43]:
#1. Revenue By Category

#Group by category
revenue_by_category = fact_orders.groupby('category').agg(
    total_revenue=('revenue','sum'),
    total_orders=('order_id','count'),
    avg_order_value=('revenue','mean')
).reset_index()

#Sort by total revenue (descending)
revenue_by_category = revenue_by_category.sort_values(by='total_revenue',ascending=False).round(2)
print(revenue_by_category)

      category  total_revenue  total_orders  avg_order_value
4  Electronics      655231.60            83          7894.36
5     Footwear      173120.00            21          8243.81
3     Clothing      120386.50            39          3086.83
6       Health       84030.75            17          4942.99
0  Accessories       82217.70            26          3162.22
7       Sports       73386.45            34          2158.42
1         Bags       69106.80            17          4065.11
2       Beauty       53675.95            49          1095.43
8   Stationery       12916.80            14           922.63

In [13]:
#export as output_revenue_by_category
revenue_by_category.to_csv(r"D:\My Work\Project\output_revenue_by_category.csv", index=False)

In [47]:
#2. Extracting year-month from order_date
fact_orders['year_month'] = fact_orders['order_date'].dt.to_period('M')
fact_orders.head()

,order_id,customer_id,customer_name,product_name,category,quantity,unit_price,discount,region,status,order_date,revenue,year_month
0,ORD-1035,C015,Arjun Nair,Pen Drive 32Gb,Electronics,2,799,5,North,Completed,2024-12-07,1518.10,2024-12
1,ORD-1174,C014,Meera Pillai,Resistance Bands,Sports,2,649,0,Unknown,Completed,2024-09-14,1298.00,2024-09
2,ORD-1066,C009,Vikram Das,Yoga Mat,Sports,4,899,0,North,Returned,2024-10-11,3596.00,2024-10
3,ORD-1101,C011,Rahul Verma,Smart Watch,Electronics,1,4999,10,South,Completed,2024-08-13,4499.10,2024-08
4,ORD-1109,C008,Neha Sharma,Protein Powder,Health,1,1899,15,South,Completed,2024-05-10,1614.15,2024-05

In [18]:
# Group by year_month and compute metrics
monthly_sales = fact_orders.groupby('year_month').agg(
    total_revenue=('revenue', 'sum'),
    total_orders=('order_id', 'count')
).reset_index()
print(monthly_sales)

   year_month  total_revenue  total_orders
0     2024-01      111020.70            20
1     2024-02      148159.25            28
2     2024-03       80849.45            22
3     2024-04       87604.35            17
4     2024-05      107706.75            28
5     2024-06       63012.90            17
6     2024-07      115468.90            29
7     2024-08      148798.05            30
8     2024-09       92992.60            19
9     2024-10      179786.15            32
10    2024-11       78221.05            24
11    2024-12       93088.95            25

In [23]:
# Calculate Month-over-Month (MoM) Growth percentage

monthly_sales['mom_growth_pct'] = (
    monthly_sales['total_revenue'].pct_change() * 100 ).round(2).fillna(0) # pct_change() → calculates % change from previous row & * 100 → converts to percentage

print(monthly_sales)

   year_month  total_revenue  total_orders  mom_growth_pct
0     2024-01      111020.70            20            0.00
1     2024-02      148159.25            28           33.45
2     2024-03       80849.45            22          -45.43
3     2024-04       87604.35            17            8.35
4     2024-05      107706.75            28           22.95
5     2024-06       63012.90            17          -41.50
6     2024-07      115468.90            29           83.25
7     2024-08      148798.05            30           28.86
8     2024-09       92992.60            19          -37.50
9     2024-10      179786.15            32           93.33
10    2024-11       78221.05            24          -56.49
11    2024-12       93088.95            25           19.01

In [25]:
# Sort chronologically
monthly_sales = monthly_sales.sort_values('year_month')
print(monthly_sales)

   year_month  total_revenue  total_orders  mom_growth_pct
0     2024-01      111020.70            20            0.00
1     2024-02      148159.25            28           33.45
2     2024-03       80849.45            22          -45.43
3     2024-04       87604.35            17            8.35
4     2024-05      107706.75            28           22.95
5     2024-06       63012.90            17          -41.50
6     2024-07      115468.90            29           83.25
7     2024-08      148798.05            30           28.86
8     2024-09       92992.60            19          -37.50
9     2024-10      179786.15            32           93.33
10    2024-11       78221.05            24          -56.49
11    2024-12       93088.95            25           19.01

In [26]:
monthly_sales.to_csv(r"D:\My Work\Project\output_monthly_sales.csv", index=False) # Export monthly sales data

In [48]:
#3. Counting distinct orders per customer

orders_per_customer = fact_orders.groupby('customer_id')['order_id'].nunique().reset_index() # Group data by customer_id and count distinct order_id
orders_per_customer.rename(columns={'order_id': 'order_count'}, inplace=True) # Rename column for clarity
print(orders_per_customer)

   customer_id  order_count
0         C001           16
1         C002           30
2         C003           14
3         C004           12
4         C005           20
5         C006           20
6         C007           20
7         C008           24
8         C009           17
9         C010           24
10        C011           21
11        C012           24
12        C013           22
13        C014           20
14        C015           16

In [45]:
# Identify one-time buyers

one_time_customers = orders_per_customer[orders_per_customer['order_count'] == 1] # Filter customers who placed only 1 order
print(one_time_customers) # Every customer likely has more than 1 order hence getting nothing in output

Empty DataFrame
Columns: [customer_id, order_count]
Index: []

In [41]:
# Calculate percentage of one-time buyers

total_customers = orders_per_customer.shape[0] # Total number of customers
one_time_count = one_time_customers.shape[0] # Number of one-time buyers
one_time_percentage = (one_time_count / total_customers) * 100 # Calculating percentage of one time buyers
print(f"Percentage of one-time buyers: {one_time_percentage:.2f}%") #Printing the result clearly

#output analysis
# Meaning: Every row = one unique order, No duplicate orders
# Now if each customer has: 2 or more orders
# Then: No one has exactly 1 order
# So: one_time_customers = EMPTY

Percentage of one-time buyers: 0.00%

In [42]:
# Exporting one-time customers list
one_time_customers.to_csv(r"D:\My Work\Project\output_churn_customers.csv", index=False)

In [55]:
#4. Business Question 4 – Average order value by Region

# Aggregate data by region
aov_by_region = fact_orders.groupby('region').agg(
    total_revenue=('revenue', 'sum'),       # Total revenue per region
    total_orders=('order_id', 'count'),     # Number of orders per region
    avg_order_value=('revenue', 'mean')     # Average order value (AOV)
).reset_index().round(2) # reset index and Round numeric values to 2 decimal places

In [56]:
# Sort regions by highest average order value
aov_by_region = aov_by_region.sort_values(
    by='avg_order_value', ascending=False)
print(aov_by_region)

    region  total_revenue  total_orders  avg_order_value
0     East      275155.35            47          5854.37
4     West      259929.50            57          4560.17
1    North      194984.15            44          4431.46
2    South      202975.90            51          3979.92
3  Unknown      391027.65           101          3871.56

In [57]:
# exporting output to CSV file
aov_by_region.to_csv(r"D:\My Work\Project\output_aov_by_region.csv", index=False)

In [58]:
#5. Returns & Cancellations

# Group by order status and count number of orders
status_summary = fact_orders.groupby('status').agg(
    total_orders=('order_id', 'count'),     # Count of orders per status
    total_revenue=('revenue', 'sum')        # Total revenue per status
).reset_index()

In [61]:
# Calculating percentage of total orders

total_orders_all = fact_orders['order_id'].count() # Get total number of orders
status_summary['order_percentage'] = (status_summary['total_orders'] / total_orders_all) * 100 # Calculate percentage contribution of each status
status_summary['order_percentage']= status_summary['order_percentage'].round(2)
print(status_summary)

      status  total_orders  total_revenue  order_percentage
0  Cancelled            40      219011.75             13.33
1  Completed           187      817847.35             62.33
2    Pending            38      135228.85             12.67
3   Returned            35      151984.60             11.67

In [64]:
# Calculating revenue loss (Returned & Cancelled)

loss_fact_orders = fact_orders[fact_orders['status'].isin(['Returned', 'Cancelled'])] # Filter only Returned and Cancelled orders
revenue_lost = loss_fact_orders['revenue'].sum() # Calculate total revenue lost
print(f"Total revenue lost due to returns and cancellations: {revenue_lost:.2f}") # Print revenue loss clearlywith 2 decimal factor

Total revenue lost due to returns and cancellations: 370996.35

In [65]:
# export summary to CSV
status_summary.to_csv(r"D:\My Work\Project\output_order_status.csv", index=False)